use vcs_provider_core::{AuthHeaderStyle, AuthKind, Capability, VcsResult, conformance};
use vcs_provider_github::{DISPLAY_NAME, PROVIDER_ID, github};

#[test]
fn github_provider_passes_common_conformance_suite() -> VcsResult<()> {
    conformance()
        .provider(github())
        .id(PROVIDER_ID)
        .display_name(DISPLAY_NAME)
        .supports([
            Capability::Repos,
            Capability::RepoGet,
            Capability::RepoList,
            Capability::RepoSearch,
            Capability::RepoBranches,
            Capability::RepoCommits,
            Capability::RepoCreate,
            Capability::RepoUpdate,
            Capability::RepoDelete,
            Capability::Issues,
            Capability::IssueGet,
            Capability::IssueList,
            Capability::IssueCreate,
            Capability::IssueUpdate,
            Capability::IssueClose,
            Capability::CodeReviews,
            Capability::CodeReviewGet,
            Capability::CodeReviewList,
            Capability::CodeReviewCreate,
            Capability::CodeReviewUpdate,
            Capability::CodeReviewMerge,
            Capability::CodeReviewClose,
            Capability::Pipelines,
            Capability::PipelineGet,
            Capability::PipelineList,
            Capability::PipelineRerun,
            Capability::PipelineCancel,
            Capability::Releases,
            Capability::ReleaseGet,
            Capability::ReleaseList,
            Capability::ReleaseCreate,
            Capability::ReleaseUpdate,
            Capability::ReleaseDelete,
        ])
        .does_not_support([
            Capability::IssueDelete,
            Capability::CodeReviewDelete,
            Capability::Organizations,
            Capability::Discussions,
            Capability::Webhooks,
            Capability::SelfHosted,
        ])
        .auth(
            AuthKind::PersonalAccessToken,
            AuthHeaderStyle::AuthorizationBearer,
        )
        .check()
}
