name: test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  workspace:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.89.0
        with:
          components: clippy,rustfmt
      - run: cargo fmt --check
      - run: cargo test
      - run: cargo clippy --all-targets --all-features -- -D warnings

  providers:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        package:
          - vcs-provider-github
          - vcs-provider-gitlab
          - vcs-provider-bitbucket
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.89.0
        with:
          components: clippy,rustfmt
      - run: cargo test --package ${{ matrix.package }}
      - run: cargo clippy --package ${{ matrix.package }} --all-targets --all-features -- -D warnings
